name: MagmaRoar
version: 8.0
main: com.example.magmaroar.MagmaRoarPlugin
api-version: 1.21
commands:
  roar:
    description: Дает Рог Магмы
    usage: /roar
  mace:
    description: Дает Легкую Булаву
    usage: /mace
  flamingbow:
    description: Дает Пылающий арбалет
    usage: /flamingbow
  blood:
    description: Дает Кровавый меч (3 в 1)
    usage: /blood
  zombietotem:
    description: Дает яйцо зомби с тотемами
    usage: /zombietotem
  zombieshield:
    description: Дает яйцо зомби со щитом
    usage: /zombieshield
  frost:
    description: Дает Морозный меч
    usage: /frost
  shadow:
    description: Дает Теневой меч
    usage: /shadow
  orbital:
    description: Дает Орбитальную пушку
    usage: /orbital
  sculkbow:
    description: Дает Скалковый арбалет
    usage: /sculkbow
  villagerstaff:
    description: Дает Посох жителя
    usage: /villagerstaff
  explosivepotion:
    description: Дает взрывные зелья (x16)
    usage: /explosivepotion
  spider:
    description: Дает Паучий клинок
    usage: /spider
  mjolnir:
    description: Дает Мьёльнир
    usage: /mjolnir
  hypnosis:
    description: Дает Жезл гипноза
    usage: /hypnosis
  scythe:
    description: Дает Косу смерти
    usage: /scythe
  ravager:
    description: Дает Рог разорителя
    usage: /ravager
  meteor:
    description: Дает Адский метеорит
    usage: /meteor
  laser:
    description: Дает Лазер
    usage: /laser
  storm:
    description: Дает Клинок бури
    usage: /storm
  excalibur:
    description: Дает Экскалибур
    usage: /excalibur
  katana:
    description: Дает Катану дракона
    usage: /katana
  reaper:
    description: Дает Косу жнеца
    usage: /reaper
  ludo:
    description: Дает Лудо-меч
    usage: /ludo