name: MagmaRoar
version: 1.0
main: me.kaidmonn.magmaroar.MagmaRoar
api-version: '1.21'
author: kaidmonngrief
description: Плагин на систему команд и 14 видов уникального оружия.

commands:
  team:
    description: Основная команда управления системой команд.
    usage: /team <create|join|invite|leave|disband|newleader|accept|deny>
    aliases: [t]
  magma:
    description: Административная команда для выдачи предметов.
    permission: magmaroar.admin
    usage: /magma <all|randomall>

permissions:
  magmaroar.admin:
    description: Позволяет использовать команду выдачи оружия.
    default: op